version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  Build-Docker-Image:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Build Docker Image"
          command: "docker build -t minikube-task-2 ."
  
  Push-Docker-Image-to-Docker-Hub:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Push Docker Image to Docker Hub"
          command: |
            echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin
            docker tag minikube-task-2 $DOCKER_HUB_USER/minikube-task-2
            docker push $DOCKER_HUB_USER/minikube-task-2
  
  start-the-minikube-deployment:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "start the minikube deployment"
          command: "ansible-playbook -i hosts playbook.yml"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - Build-Docker-Image:
          requires:
            - say-hello
      - Push-Docker-Image-to-Docker-Hub:
          requires:
            - Build-Docker-Image
      - start-the-minikube-deployment:
          requires:
            - Push-Docker-Image-to-Docker-Hub
