version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  Build-Docker-Image:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Specify your Docker version
          docker_layer_caching: true  # Optional for caching
      - run:
          name: "Build Docker Image"
          command: "docker build -t minikube-task-2 ."
  
  Push-Docker-Image-to-Docker-Hub:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Specify your Docker version
          docker_layer_caching: true  # Optional for caching
      - run:
          name: "Push Docker Image to Docker Hub"
          command: |
            docker images
            echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin
            docker tag minikube-task-2 $DOCKER_HUB_USER/minikube-task-2
            docker push $DOCKER_HUB_USER/minikube-task-2
  
  start-the-minikube-deployment:
    docker:
      - image: ubuntu-2004:202010-01  # Use a Python image to easily install Ansible
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Specify your Docker version
          docker_layer_caching: true  # Optional for caching
      - run:
          name: "install Minikube Deployment"
          command: |
            echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
            sudo dpkg -i minikube_latest_amd64.deb
            minikube start --vm-driver=docker --kubernetes-version=v1.19.0

      - run:
          name: "Start the Minikube Deployment"
          command: |
            minikube start --driver=docker
            minikube kubectl -- apply -f nginx-deployment.yaml
            minikube service my-service
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - Build-Docker-Image:
          requires:
            - say-hello
      - Push-Docker-Image-to-Docker-Hub:
          requires:
            - Build-Docker-Image
      - start-the-minikube-deployment:
          requires:
            - Push-Docker-Image-to-Docker-Hub
